/**
 * Type Action For Home Magazine
 */
export const SHOW_LIST_SITE = 'SHOW_LIST_SITE';
export const SHOW_MODAL = 'SHOW_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const ON_CHANGE_INPUT = 'ON_CHANGE_INPUT';
export const SUBMIT_CONFIG = 'SUBMIT_CONFIG';
export const DELETE_SITE = 'DELETE_SITE';
export const SEARCH_SITE = "SEARCH_SITE";

/**
 * Type Action For site magazine
 */

export const SHOW_ALL_SITE = 'SHOW_ALL_SITE';
export const SHOW_FLAT_FORM = 'SHOW_FLAT_FORM';
export const SHOW_RELOAD_PAGE = 'SHOW_RELOAD_PAGE';
export const EVENT_DOWNLOAD = 'EVENT_DOWNLOAD';
export const EVENT_VIEW = 'EVENT_VIEW';
export const EVENT_DELETE = 'EVENT_DELETE';
export const EVENT_CONFIG = 'EVENT_CONFIG';
export const SHOW_TAB = 'SHOW_TAB';
export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL_CONFIG = "CLOSE_MODAL_CONFIG";
export const SEARCH_ISSUE = "SEARCH_ISSUE";
export const CHANGE_LOADDING = "CHANGE_LOADDING";

/**
 * Type Action For site magazine
 */

export const SHOW_ALL_ISSUE = 'SHOW_ALL_ISSUE';
export const SEARCH_STORY = 'SEARCH_STORY';
export const BUTTON_CHANGE_FLATFORM = 'BUTTON_CHANGE_FLATFORM';
export const BUTTON_CHANGE_MODE = 'BUTTON_CHANGE_MODE';
export const BUTTON_CHANGE_WIDTH = 'BUTTON_CHANGE_WIDTH';
export const BUTTON_CHANGE_SIZE = 'BUTTON_CHANGE_SIZE';
export const ZOOM_FRAME = 'ZOOM_FRAME';
export const CHANGE_URL_IFRAME = 'CHANGE_URL_IFRAME';
export const CHANGE_LAYOUT = 'CHANGE_LAYOUT';
export const CHANGE_SWIPE = 'CHANGE_SWIPE';

export const DOWNLOAD_SUCCESS = 'DOWNLOAD_SUCCESS';
export const DOWNLOAD_REQUEST = 'DOWNLOAD_REQUEST';
export const DOWNLOAD_FAILED = 'DOWNLOAD_FAILED';

export const DELETED_ISSUE_SUCCESS = 'DELETED_ISSUE_SUCCESS';
export const DELETED_ISSUE_REQUEST = 'DELETED_ISSUE_REQUEST';
export const DELETED_ISSUE_FAILED = 'DELETED_ISSUE_FAILED';

/**
 * Fetch Data
 * 
 */

export const FETCH_DATA_SUCCCESS_MAGAZINE = "FETCH_DATA_SUCCCESS_MAGAZINE";
export const FETCH_DATA_REQUESTED_MAGAZINE = "FETCH_DATA_REQUESTED_MAGAZINE";
export const FETCH_DATA_FAILED_MAGAZINE = "FETCH_DATA_FAILED_MAGAZINE";

export const FETCH_DATA_SUCCCESS_SITE = "FETCH_DATA_SUCCCESS_SITE";
export const FETCH_DATA_REQUESTED_SITE = "FETCH_DATA_REQUESTED_SITE";
export const FETCH_DATA_FAILED_SITE = "FETCH_DATA_FAILED_SITE";


export const FETCH_DATA_SUCCCESS_ISSUE = "FETCH_DATA_SUCCCESS_ISSUE";
export const FETCH_DATA_REQUESTED_ISSUE = "FETCH_DATA_REQUESTED_ISSUE";
export const FETCH_DATA_FAILED_ISSUE = "FETCH_DATA_FAILED_ISSUE";

export const FETCH_INFO_CONFIG_SUCCESS = "FETCH_INFO_CONFIG_SUCCESS";
export const FETCH_INFO_CONFIG_REQUEST = "FETCH_INFO_CONFIG_REQUESTED";
export const FETCH_INFO_CONFIG_FAILED = "FETCH_INFO_CONFIG_FAILED";